import type { ExportManifest } from "../lib/types";

type FooterProps = {
  manifest: ExportManifest | null;
};

export default function Footer({ manifest }: FooterProps) {
  return (
    <footer className="border-t border-slate-200 bg-white">
      <div className="mx-auto grid max-w-7xl gap-8 px-4 py-10 sm:px-6 lg:grid-cols-3 lg:px-8">
        <div>
          <div className="font-heading text-lg font-bold text-slate-950">About this site</div>
          <p className="mt-3 max-w-md text-sm leading-6 text-slate-600">
            This site presents exported TASE filing summaries generated by a deterministic Python workflow and packaged
            as static assets.
          </p>
        </div>

        <div>
          <div className="font-heading text-lg font-bold text-slate-950">Dataset</div>
          <dl className="mt-3 space-y-2 text-sm text-slate-600">
            <div className="flex justify-between gap-4">
              <dt>Reports</dt>
              <dd className="font-mono text-slate-900">{manifest?.report_count ?? "..."}</dd>
            </div>
            <div className="flex justify-between gap-4">
              <dt>Form templates</dt>
              <dd className="font-mono text-slate-900">{manifest?.form_count ?? "..."}</dd>
            </div>
            <div className="flex justify-between gap-4">
              <dt>Missing PDFs</dt>
              <dd className="font-mono text-slate-900">{manifest?.missing_pdf_count ?? "..."}</dd>
            </div>
          </dl>
        </div>

        <div>
          <div className="font-heading text-lg font-bold text-slate-950">Delivery model</div>
          <p className="mt-3 text-sm leading-6 text-slate-600">
            Static assets only. No runtime database, no server-side mutations, and a deployment path that fits a
            CDN-backed host.
          </p>
        </div>
      </div>
    </footer>
  );
}
